### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by mazh91** [cspurk/audacious-plugin-fadeout#1]
I'm getting the following errors on Ubuntu Xenial (I don't intend on using extra gtk packages also my audacious version is 3.6.2):

> $ cmake . -DCMAKE_INSTALL_PREFIX=$HOME
> -- Checking for one of the modules 'audacious>=3.4.0'
> CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:578 (message):
>   None of the required 'audacious>=3.4.0' found
> Call Stack (most recent call first):
>   CMakeLists.txt:45 (PKG_SEARCH_MODULE)
> 
> 
> -- Checking for one of the modules 'gtk+-3.0>=3.0.0'
> CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:578 (message):
>   None of the required 'gtk+-3.0>=3.0.0' found
> Call Stack (most recent call first):
>   CMakeLists.txt:46 (PKG_SEARCH_MODULE)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/milad/Downloads/audacious-plugin-fadeout-master/CMakeFiles/CMakeOutput.log".
>

**Comment by mazh91** [comment]
The solution was to build the following packages:

`# aptitude install audacious-dev build-essential libgtk-3-dev`

However, this will result in other compilation issues. I wish this project wasn't already dead.

**Comment by cspurk** [comment]
Thanks for your bug report and sorry for the long silence. I have updated the project README now to include a note on how the build dependencies can be installed on Ubuntu. Additionally, I have made a new plugin release which should work with more recent versions of Audacious.
